### ISSUE TITLE
fangtang command not found after installation

### ISSUE THREAD

**Issue by echocho** [ceclinux/custom_omz_plugins#1]
I followed the guide step by step but still there seems to be something wrong. After installation, fangtang command  was not found.

#How I tried:
1. cd custom_omz_plugins AND ./install.sh
2. vim ~/.zshrc AND added 'fangtang' to existing plugins=(git, blah blah blah)
3. obtained my SCKEY AND vim ~/.zshrc AND added 'export SCKEY=blah blah blah' at the end of the file
4. opened a new terminal AND entered 'fangtang du -a'
5. 'zsh: command not found: fangtang'

I've double checked and have modified .zshrc file accordingly. 

#Configuration:
MacOS 10.13.6
Shell: zsh

**Comment by ceclinux** [comment]
You should add `fangtang_notification`  to your plugins list, not `fangtang`

**Comment by echocho** [comment]
Well, you should state that in your README, my friend. And I'll make a pull request.
